# CREATE DATABASE SERVIDOR;
# USE SERVIDOR;

CREATE TABLE Item_Pedido (
  idITEM_PRODUTO            INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PEDIDO_idPEDIDO           INT,
  PEDIDO_MODULO_idMODULO    INT,
  ESTOQUE_PRODUTO_idESTOQUE INT,
  QUANTIDADE                INT
);

CREATE TABLE Estoque_Produto (

  idESTOQUE_PRODUTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODIGO_PRODUTO    INT,
  NOME_PRODUTO      VARCHAR(255),
  DESCRICAO_PRODUTO VARCHAR(255),
  QUANTIDADE        INT,
  PRECO             DECIMAL(10, 2)
);

CREATE TABLE Pedido (

  idPEDIDO        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MODULO_idMODULO INT,
  DATA_2          DATE,
  VALOR_COMPRA    DECIMAL(10, 2),
  FINALIZADO      VARCHAR(1)
);

CREATE TABLE Modulo (

  idMODULO      INT PRIMARY KEY,
  CODIGO_MODULO INT,
  STATUS_2      VARCHAR(1)
);


ALTER TABLE Item_Pedido ADD CONSTRAINT fk_PEDIDO_idPEDIDO FOREIGN KEY (PEDIDO_idPEDIDO) REFERENCES Pedido (idPEDIDO);

ALTER TABLE Item_Pedido ADD CONSTRAINT fk_PEDIDO_MODULO_idMODULO FOREIGN KEY (PEDIDO_MODULO_idMODULO) REFERENCES Modulo (idMODULO);

ALTER TABLE Item_Pedido ADD CONSTRAINT fk_ESTOQUE_PRODUTO_idESTOQUE FOREIGN KEY (ESTOQUE_PRODUTO_idESTOQUE) REFERENCES Estoque_Produto (idESTOQUE_PRODUTO);

ALTER TABLE Pedido ADD CONSTRAINT fk_MODULO_idMODULO FOREIGN KEY (MODULO_idMODULO) REFERENCES Modulo (idMODULO);